name:                parse-pcre2
version:             0.1.0.1
github:              "david-wahlstedt/parse-pcre2"
license:             BSD-3-Clause
author:              "David Wahlstedt"
maintainer:          "david.wahlstedt@gmail.com"
copyright:           "David Wahlstedt"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/david-wahlstedt/parse-pcre2#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- mtl
- pretty-show

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -XLambdaCase

library:
  source-dirs:
  - src
  - code_gen
  - generated

executables:
  parse-pcre2:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parse-pcre2

tests:
  parse-pcre2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parse-pcre2
